// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBw8B0Do--f4y7SEJOSRas2VZCERNF_VDY',
    appId: '1:859938357630:web:f127d67ebccbb4368ab32f',
    messagingSenderId: '859938357630',
    projectId: 'applied-primacy-294221',
    authDomain: 'applied-primacy-294221.firebaseapp.com',
    storageBucket: 'applied-primacy-294221.firebasestorage.app',
    measurementId: 'G-RT5CGZX8CG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBh1lmgeDHMkqhdk_3S80uub_ygbR6ChSY',
    appId: '1:859938357630:android:7fcda5819432e2de8ab32f',
    messagingSenderId: '859938357630',
    projectId: 'applied-primacy-294221',
    storageBucket: 'applied-primacy-294221.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXrWSZCco2lF6bX0e_UzpbK3s3eSrXm_c',
    appId: '1:859938357630:ios:eb9317100ffdc1818ab32f',
    messagingSenderId: '859938357630',
    projectId: 'applied-primacy-294221',
    storageBucket: 'applied-primacy-294221.firebasestorage.app',
    androidClientId: '859938357630-gljtck19gov495lfi9u8nihd71kjv2st.apps.googleusercontent.com',
    iosClientId: '859938357630-7nge2n09jkqvp3vh41k0qf7g1rfdgfnb.apps.googleusercontent.com',
    iosBundleId: 'com.badbird.treez',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXrWSZCco2lF6bX0e_UzpbK3s3eSrXm_c',
    appId: '1:859938357630:ios:eb9317100ffdc1818ab32f',
    messagingSenderId: '859938357630',
    projectId: 'applied-primacy-294221',
    storageBucket: 'applied-primacy-294221.firebasestorage.app',
    androidClientId: '859938357630-gljtck19gov495lfi9u8nihd71kjv2st.apps.googleusercontent.com',
    iosClientId: '859938357630-7nge2n09jkqvp3vh41k0qf7g1rfdgfnb.apps.googleusercontent.com',
    iosBundleId: 'com.badbird.treez',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBw8B0Do--f4y7SEJOSRas2VZCERNF_VDY',
    appId: '1:859938357630:web:916ca76ed9769ff68ab32f',
    messagingSenderId: '859938357630',
    projectId: 'applied-primacy-294221',
    authDomain: 'applied-primacy-294221.firebaseapp.com',
    storageBucket: 'applied-primacy-294221.firebasestorage.app',
    measurementId: 'G-JVCNC7681P',
  );

}